markdown: rdiscount
pygments: true
plugins: ./_plugins

title: fofore
url: http://fofore.github.com
feed: /atom.xml
author:
    name: fofore
    email: qianminming@gmail.com
description: 这里是个开始
